spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
      defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: "1111"
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

